hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpm reload -n")
    hl.exec_cmd("waybar -c $HOME/.config/waybar/config")
    hl.exec_cmd("openrgb --startminimized -p $HOME/.config/OpenRGB/1.orp")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("env QT_QPA_PLATFORM=xcb copyq --start-server")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("sleep 3 && $HOME/.config/hypr/quodlibet-duck.sh --daemonize")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("hash dbus-update-activation-environment 2>/dev/null && dbus-update-activation-environment --systemd --all")

    hl.exec_cmd("swaync")
    hl.exec_cmd("snappy-switcher --daemon")
    hl.exec_cmd("sleep 5 && noisetorch -s alsa_input.usb-R__DE_Microphones_R__DE_NT-USB_Mini_73B04B6B-00.mono-fallback -i -t 95")
end)
